version: '3.8'

services:
  web:
    build: ./services/web
    command: gunicorn --bind 0.0.0.0:8002 wsgi:app
    volumes:
      - ./services/web:/usr/src/app/
    expose:
      - 8002
    env_file:
      - ./.env.prod
      
  nginx:
    build: ./services/nginx
    ports: 
        - 1337:80
    depends_on:
        - web
        
